# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-03 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
