# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-03 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_auto_20160128_1413'),
        ('geo', '0002_marker_description'),
    ]

    operations = [
    ]
